version: 2.1

orbs:
  utils: coda/utils@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

commands:


jobs:
  integration-test-notify:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - utils/notify:
          on_success: true

  integration-test-slack:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - utils/slack-notify-waiting-for-approval:
          slack_bot_token: ${PUSH_REMINDER_BOT_TOKEN}

  integration-test-cancel-older-jobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - utils/cancel-older-awaiting-approvals:
          circle_token: ${CIRCLECI_API_TOKEN}

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/pack 
      - shellcheck/check:
          dir: ./src/scripts
      - bats/run:
          path: ./src/tests
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      # Publish development version of the orb.
      - orb-tools/publish-dev:
          orb-name: coda/utils
          context: orb-publishing 
          requires: [hold-for-dev-publish]
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-notify
      - integration-test-slack
      - integration-test-cancel-older-jobs
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: coda/utils
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-notify
            - integration-test-slack
            - integration-test-cancel-older-jobs

