version: 2.1

executors:
  validate:
    resource_class: small
    docker:
      - image: circleci/circleci-cli:latest
jobs:
  validate:
    executor: validate
    steps:
      - checkout
      - run:
          name: "Validate ORB config"
          command: circleci orb validate config.yml

workflows:
  version: 2
  commit_validation:
    jobs:
      - validate

